// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SenNotes.Migrations.Context;

#nullable disable

namespace SenNotes.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018063240_InitalMigrtaions")]
    partial class InitalMigrtaions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("SenNotes.Common.Models.SettingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingModels");
                });

            modelBuilder.Entity("SenNotes.Common.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Files")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskModels");
                });
#pragma warning restore 612, 618
        }
    }
}
